Repository dentsusoken/iPLAss, pull requests merged in 2024-05, with the labels that each got.

#1482 AdminConsoleにてダイアログで色を選択できるように修正
  iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/data/tenant/BaseTenantDS.java
  iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/data/tenant/TenantColType.java
  iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/tenant/BaseTenantPropertyEditDialog.java
Labels: enhancement

#1491 Webhook、DefaultWebhookResponseHandlerのステータスコードの判定がおかしい
  iplass-core/src/main/java/org/iplass/mtp/impl/webhook/DefaultWebhookResponseHandler.java
Labels: bug

#1493 Webhook、DefaultWebhookResponseHandlerのステータスコードの判定がおかしい
  iplass-core/src/main/java/org/iplass/mtp/impl/webhook/DefaultWebhookResponseHandler.java
Labels: bug

#1504 GEM、PDF.jsバージョンアップ
  iplass-gem/src/main/resources/META-INF/resources/jsp/gem/binary/pdfviewer.jsp
  iplass-gem/src/main/resources/META-INF/resources/scripts/gem/plugin/pdfjs/blank.pdf
  iplass-gem/src/main/resources/META-INF/resources/scripts/gem/plugin/pdfjs/web/viewer.js
  sharedlibs.gradle
Labels: dependency update

#1509 GEM、PDF.jsバージョンアップ
  iplass-gem/src/main/resources/META-INF/resources/jsp/gem/binary/pdfviewer.jsp
  iplass-gem/src/main/resources/META-INF/resources/scripts/gem/plugin/pdfjs/blank.pdf
  iplass-gem/src/main/resources/META-INF/resources/scripts/gem/plugin/pdfjs/web/viewer.js
  sharedlibs.gradle
Labels: dependency update

#1511 GEM、PDF.jsバージョンアップ
  iplass-gem/src/main/resources/META-INF/resources/jsp/gem/binary/pdfviewer.jsp
  iplass-gem/src/main/resources/META-INF/resources/scripts/gem/plugin/pdfjs/blank.pdf
  iplass-gem/src/main/resources/META-INF/resources/scripts/gem/plugin/pdfjs/web/viewer.js
  sharedlibs.gradle
Labels: dependency update
